import { randomUUID } from 'node:crypto';
import type { RecommendationResult } from '@crop-copilot/contracts';

export interface RecommendationPipelineInput {
  inputId: string;
  userId: string;
  jobId: string;
}

/**
 * Placeholder recommendation pipeline for async orchestration.
 * Future phases will replace this with real retrieval, generation, and validation stages.
 */
export async function runRecommendationPipeline(
  input: RecommendationPipelineInput
): Promise<RecommendationResult> {
  const now = new Date().toISOString();

  return {
    recommendationId: randomUUID(),
    confidence: 0.7,
    diagnosis: {
      condition: 'analysis_pending',
      summary:
        'Asynchronous recommendation generated by pipeline scaffold. Retrieval/generation will be integrated in later phases.',
      generatedAt: now,
      inputId: input.inputId,
      userId: input.userId,
      jobId: input.jobId,
    },
    sources: [],
    modelUsed: 'pipeline-scaffold-v1',
  };
}
